<?php
/* template head */
if (function_exists('PluginStr')===false)
	$this->getLoader()->loadPlugin('PluginStr');
/* end template head */ ob_start(); /* template body */ ;
if ((isset($this->scope["MAINNAV"]) ? $this->scope["MAINNAV"] : null)) {
?>


<nav>
  <div id="main-nav" class="<?php if ((isset($this->scope["ADMIN"]) ? $this->scope["ADMIN"] : null) || (isset($this->scope["INSTITUTIONALADMIN"]) ? $this->scope["INSTITUTIONALADMIN"] : null) || (isset($this->scope["STAFF"]) ? $this->scope["STAFF"] : null) || (isset($this->scope["INSTITUTIONALSTAFF"]) ? $this->scope["INSTITUTIONALSTAFF"] : null)) {
?>adminnav<?php 
}?> nav collapse navbar-collapse nav-main" role="tabcard">
    <ul id="nav" class="nav navbar-nav">
        <?php $_fh6_data = (is_string($tmp=(isset($this->scope["MAINNAV"]) ? $this->scope["MAINNAV"] : null)) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);$this->globals["foreach"]['menu'] = array("index"		=> 0,);$_fh6_glob =& $this->globals["foreach"]['menu'];if ($this->isTraversable($_fh6_data) == true){foreach ($_fh6_data as $this->scope['item']){/* -- foreach start output */?><li class="<?php if ((isset($this->scope["item"]["path"]) ? $this->scope["item"]["path"]:null)) {
echo (is_string($tmp=$this->scope["item"]["path"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);
}
else {?>dashboard<?php }
if ((isset($this->scope["item"]["selected"]) ? $this->scope["item"]["selected"]:null)) {?> active<?php }?>"><a href="<?php echo (is_string($tmp=$this->scope["WWWROOT"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);
echo (is_string($tmp=$this->scope["item"]["url"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"<?php if ((isset($this->scope["item"]["accesskey"]) ? $this->scope["item"]["accesskey"]:null)) {?> accesskey="<?php echo (is_string($tmp=$this->scope["item"]["accesskey"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"<?php }?> class="<?php if ((isset($this->scope["item"]["path"]) ? $this->scope["item"]["path"]:null)) {
echo (is_string($tmp=$this->scope["item"]["path"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);
}
else {?>dashboard<?php }?> <?php if ((isset($this->scope["item"]["submenu"]) ? $this->scope["item"]["submenu"]:null)) {?>menu-dropdown-toggle<?php }?>"><?php if ((isset($this->scope["item"]["iconclass"]) ? $this->scope["item"]["iconclass"]:null)) {?><span class="icon icon-<?php echo (is_string($tmp=$this->scope["item"]["iconclass"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>" role="presentation" aria-hidden="true"></span><?php }
if ((isset($this->scope["item"]["accessibletitle"]) ? $this->scope["item"]["accessibletitle"]:null)) {?><span role="presentation" aria-hidden="true"><?php }
echo (is_string($tmp=$this->scope["item"]["title"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);
if ((isset($this->scope["item"]["accessibletitle"]) ? $this->scope["item"]["accessibletitle"]:null)) {?></span><span class="accessible-hidden sr-only">(<?php echo (is_string($tmp=$this->scope["item"]["accessibletitle"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>)</span><?php }?></a><?php if ((isset($this->scope["item"]["submenu"]) ? $this->scope["item"]["submenu"]:null)) {?><button type="button" class="navbar-showchildren navbar-toggle <?php if (! (isset($this->scope["item"]["selected"]) ? $this->scope["item"]["selected"]:null)) {?>collapsed<?php }?>" data-toggle="collapse" data-parent="#nav" data-target="#childmenu-<?php echo (is_string($tmp=$this->globals["foreach"]["menu"]["index"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"><span class="icon icon-chevron-down" role="presentation" aria-hidden="true"></span><span class="nav-title sr-only"><?php echo PluginStr($this, "showmenu", "mahara", null, "".(is_string($tmp=(isset($this->scope["item"]["title"]) ? $this->scope["item"]["title"]:null)) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp)."", null, null, null);?></span></button><?php }
if ((isset($this->scope["item"]["submenu"]) ? $this->scope["item"]["submenu"]:null)) {?><ul id="childmenu-<?php echo (is_string($tmp=$this->globals["foreach"]["menu"]["index"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>" class="<?php if ((isset($this->scope["item"]["selected"]) ? $this->scope["item"]["selected"]:null)) {?> show<?php }?> collapse child-nav" role="menu"><?php $_fh5_data = (is_string($tmp=(isset($this->scope["item"]["submenu"]) ? $this->scope["item"]["submenu"]:null)) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);if ($this->isTraversable($_fh5_data) == true){foreach ($_fh5_data as $this->scope['subitem']){/* -- foreach start output */?><li class="<?php if ((isset($this->scope["subitem"]["selected"]) ? $this->scope["subitem"]["selected"]:null)) {?>active <?php }
if ((isset($this->scope["subitem"]["submenu"]) ? $this->scope["subitem"]["submenu"]:null)) {?>has-sub <?php }?>"><a href="<?php echo (is_string($tmp=$this->scope["WWWROOT"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);
echo (is_string($tmp=$this->scope["subitem"]["url"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"<?php if ((isset($this->scope["subitem"]["accesskey"]) ? $this->scope["subitem"]["accesskey"]:null)) {?> accesskey="<?php echo (is_string($tmp=$this->scope["subitem"]["accesskey"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"<?php }?>><?php echo (is_string($tmp=$this->scope["subitem"]["title"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?></a><?php if ((isset($this->scope["subitem"]["submenu"]) ? $this->scope["subitem"]["submenu"]:null)) {?><ul class="dropdown-tertiary"><?php $_fh4_data = (is_string($tmp=(isset($this->scope["subitem"]["submenu"]) ? $this->scope["subitem"]["submenu"]:null)) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);if ($this->isTraversable($_fh4_data) == true){foreach ($_fh4_data as $this->scope['tertiaryitem']){/* -- foreach start output */?><li<?php if ((isset($this->scope["tertiaryitem"]["selected"]) ? $this->scope["tertiaryitem"]["selected"]:null)) {?> class="selected"<?php }?>><a href="<?php echo (is_string($tmp=$this->scope["WWWROOT"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);
echo (is_string($tmp=$this->scope["tertiaryitem"]["url"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"<?php if ((isset($this->scope["tertiaryitem"]["accesskey"]) ? $this->scope["tertiaryitem"]["accesskey"]:null)) {?> accesskey="<?php echo (is_string($tmp=$this->scope["tertiaryitem"]["accesskey"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"<?php }?>><?php echo (is_string($tmp=$this->scope["tertiaryitem"]["title"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?></a></li><?php /* -- foreach end output */}}?></ul><?php }?></li><?php /* -- foreach end output */}}?></ul><?php }?></li><?php /* -- foreach end output */$_fh6_glob["index"]+=1;}}?>

    </ul>
  </div>
</nav>
<nav>
  <div id="main-nav-admin" class="<?php if ((isset($this->scope["ADMIN"]) ? $this->scope["ADMIN"] : null) || (isset($this->scope["INSTITUTIONALADMIN"]) ? $this->scope["INSTITUTIONALADMIN"] : null) || (isset($this->scope["STAFF"]) ? $this->scope["STAFF"] : null) || (isset($this->scope["INSTITUTIONALSTAFF"]) ? $this->scope["INSTITUTIONALSTAFF"] : null)) {
?>adminnav<?php 
}?> nav collapse navbar-collapse nav-main-admin" role="tabcard">
    <ul id="navadmin" class="nav navbar-nav">
    <?php $_fh9_data = (is_string($tmp=(isset($this->scope["MAINNAVADMIN"]) ? $this->scope["MAINNAVADMIN"] : null)) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);$this->globals["foreach"]['menu'] = array("index"		=> 0,);$_fh9_glob =& $this->globals["foreach"]['menu'];if ($this->isTraversable($_fh9_data) == true){foreach ($_fh9_data as $this->scope['item']){/* -- foreach start output */?><li class="<?php if ((isset($this->scope["item"]["path"]) ? $this->scope["item"]["path"]:null)) {
echo (is_string($tmp=$this->scope["item"]["path"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);
}
else {?>dashboard<?php }
if ((isset($this->scope["item"]["selected"]) ? $this->scope["item"]["selected"]:null)) {?> active<?php }?>"><a href="<?php echo (is_string($tmp=$this->scope["WWWROOT"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);
echo (is_string($tmp=$this->scope["item"]["url"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"<?php if ((isset($this->scope["item"]["accesskey"]) ? $this->scope["item"]["accesskey"]:null)) {?> accesskey="<?php echo (is_string($tmp=$this->scope["item"]["accesskey"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"<?php }?> class="<?php if ((isset($this->scope["item"]["path"]) ? $this->scope["item"]["path"]:null)) {
echo (is_string($tmp=$this->scope["item"]["path"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);
}
else {?>dashboard<?php }?> <?php if ((isset($this->scope["item"]["submenu"]) ? $this->scope["item"]["submenu"]:null)) {?>menu-dropdown-toggle<?php }?>"><?php if ((isset($this->scope["item"]["iconclass"]) ? $this->scope["item"]["iconclass"]:null)) {?><span class="icon icon-<?php echo (is_string($tmp=$this->scope["item"]["iconclass"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>" role="presentation" aria-hidden="true"></span><?php }
if ((isset($this->scope["item"]["accessibletitle"]) ? $this->scope["item"]["accessibletitle"]:null)) {?><span aria-hidden="true" role="presentation"><?php }
echo (is_string($tmp=$this->scope["item"]["title"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);
if ((isset($this->scope["item"]["accessibletitle"]) ? $this->scope["item"]["accessibletitle"]:null)) {?></span><span class="accessible-hidden sr-only">(<?php echo (is_string($tmp=$this->scope["item"]["accessibletitle"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>)</span><?php }?></a><?php if ((isset($this->scope["item"]["submenu"]) ? $this->scope["item"]["submenu"]:null)) {?><button type="button" class="navbar-showchildren navbar-toggle <?php if (! (isset($this->scope["item"]["selected"]) ? $this->scope["item"]["selected"]:null)) {?>collapsed<?php }?>" data-toggle="collapse" data-parent="#navadmin" data-target="#adminchildmenu-<?php echo (is_string($tmp=$this->globals["foreach"]["menu"]["index"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"><span class="icon icon-chevron-down" role="presentation" aria-hidden="true"></span><span class="nav-title sr-only"><?php echo PluginStr($this, "showmenu", "mahara", null, "".(is_string($tmp=(isset($this->scope["item"]["title"]) ? $this->scope["item"]["title"]:null)) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp)."", null, null, null);?></span></button><?php }
if ((isset($this->scope["item"]["submenu"]) ? $this->scope["item"]["submenu"]:null)) {?><ul id="adminchildmenu-<?php echo (is_string($tmp=$this->globals["foreach"]["menu"]["index"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>" class="<?php if ((isset($this->scope["item"]["selected"]) ? $this->scope["item"]["selected"]:null)) {?> show<?php }?> collapse child-nav" role="menu"><?php $_fh8_data = (is_string($tmp=(isset($this->scope["item"]["submenu"]) ? $this->scope["item"]["submenu"]:null)) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);if ($this->isTraversable($_fh8_data) == true){foreach ($_fh8_data as $this->scope['subitem']){/* -- foreach start output */?><li class="<?php if ((isset($this->scope["subitem"]["selected"]) ? $this->scope["subitem"]["selected"]:null)) {?>active <?php }
if ((isset($this->scope["subitem"]["submenu"]) ? $this->scope["subitem"]["submenu"]:null)) {?>has-sub <?php }?>"><a href="<?php echo (is_string($tmp=$this->scope["WWWROOT"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);
echo (is_string($tmp=$this->scope["subitem"]["url"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"<?php if ((isset($this->scope["subitem"]["accesskey"]) ? $this->scope["subitem"]["accesskey"]:null)) {?> accesskey="<?php echo (is_string($tmp=$this->scope["subitem"]["accesskey"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"<?php }?>><?php echo (is_string($tmp=$this->scope["subitem"]["title"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?></a><?php if ((isset($this->scope["subitem"]["submenu"]) ? $this->scope["subitem"]["submenu"]:null)) {?><ul class="dropdown-tertiary"><?php $_fh7_data = (is_string($tmp=(isset($this->scope["subitem"]["submenu"]) ? $this->scope["subitem"]["submenu"]:null)) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);if ($this->isTraversable($_fh7_data) == true){foreach ($_fh7_data as $this->scope['tertiaryitem']){/* -- foreach start output */?><li<?php if ((isset($this->scope["tertiaryitem"]["selected"]) ? $this->scope["tertiaryitem"]["selected"]:null)) {?> class="selected"<?php }?>><a href="<?php echo (is_string($tmp=$this->scope["WWWROOT"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);
echo (is_string($tmp=$this->scope["tertiaryitem"]["url"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"<?php if ((isset($this->scope["tertiaryitem"]["accesskey"]) ? $this->scope["tertiaryitem"]["accesskey"]:null)) {?> accesskey="<?php echo (is_string($tmp=$this->scope["tertiaryitem"]["accesskey"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"<?php }?>><?php echo (is_string($tmp=$this->scope["tertiaryitem"]["title"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?></a></li><?php /* -- foreach end output */}}?></ul><?php }?></li><?php /* -- foreach end output */}}?></ul><?php }?></li><?php /* -- foreach end output */$_fh9_glob["index"]+=1;}}?>

    </ul>
  </div>
</nav>
<?php 
}?>


<?php if ((isset($this->scope["RIGHTNAV"]) ? $this->scope["RIGHTNAV"] : null)) {
?>

<nav>
  <div id="main-nav-user" class="<?php if ((isset($this->scope["ADMIN"]) ? $this->scope["ADMIN"] : null) || (isset($this->scope["INSTITUTIONALADMIN"]) ? $this->scope["INSTITUTIONALADMIN"] : null) || (isset($this->scope["STAFF"]) ? $this->scope["STAFF"] : null) || (isset($this->scope["INSTITUTIONALSTAFF"]) ? $this->scope["INSTITUTIONALSTAFF"] : null)) {


}?> nav collapse navbar-collapse nav-main-user" role="tabcard">
    <ul id="navuser" class="nav navbar-nav">
      <?php $_fh13_data = (is_string($tmp=(isset($this->scope["RIGHTNAV"]) ? $this->scope["RIGHTNAV"] : null)) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);if ($this->isTraversable($_fh13_data) == true){foreach ($_fh13_data as $this->scope['item']){/* -- foreach start output */?><li class="<?php echo (is_string($tmp=$this->scope["item"]["path"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);
if ((isset($this->scope["item"]["selected"]) ? $this->scope["item"]["selected"]:null)) {?> active<?php }
if ((isset($this->scope["item"]["class"]) ? $this->scope["item"]["class"]:null)) {?> <?php echo (is_string($tmp=$this->scope["item"]["class"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);
}?>  <?php if ((isset($this->scope["item"]["iconclass"]) ? $this->scope["item"]["iconclass"]:null)) {?>has-icon<?php }?> dropdown-item"><a <?php if ((isset($this->scope["item"]["linkid"]) ? $this->scope["item"]["linkid"]:null)) {?>id="<?php echo (is_string($tmp=$this->scope["item"]["linkid"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"<?php }?> <?php if ((isset($this->scope["item"]["accesskey"]) ? $this->scope["item"]["accesskey"]:null)) {?>accesskey="<?php echo (is_string($tmp=$this->scope["item"]["accesskey"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>" <?php }
if ((isset($this->scope["item"]["aria"]) ? $this->scope["item"]["aria"]:null)) {
$_fh10_data = (is_string($tmp=(isset($this->scope["item"]["aria"]) ? $this->scope["item"]["aria"]:null)) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);if ($this->isTraversable($_fh10_data) == true){foreach ($_fh10_data as $this->scope['key']=>$this->scope['value']){/* -- foreach start output */?>aria-<?php echo (is_string($tmp=$this->scope["key"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>="<?php echo (is_string($tmp=$this->scope["value"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>" <?php /* -- foreach end output */}}
}?>href="<?php if ((isset($this->scope["item"]["wwwroot"]) ? $this->scope["item"]["wwwroot"]:null)) {
echo (is_string($tmp=$this->scope["item"]["wwwroot"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);
}
else {
echo (is_string($tmp=$this->scope["WWWROOT"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);
}
echo (is_string($tmp=$this->scope["item"]["url"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>" class="<?php if ((isset($this->scope["item"]["submenu"]) ? $this->scope["item"]["submenu"]:null)) {?>menu-dropdown-toggle<?php }?>"><?php if ((isset($this->scope["item"]["iconclass"]) ? $this->scope["item"]["iconclass"]:null)) {?><span class="icon icon-<?php echo (is_string($tmp=$this->scope["item"]["iconclass"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>" role="presentation" aria-hidden="true"></span><?php }?><span class="nav-title"><?php echo (is_string($tmp=$this->scope["item"]["title"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?></span></a><?php if ((isset($this->scope["item"]["submenu"]) ? $this->scope["item"]["submenu"]:null)) {?><button type="button" class="navbar-showchildren navbar-toggle <?php if (! (isset($this->scope["item"]["selected"]) ? $this->scope["item"]["selected"]:null)) {?>collapsed<?php }?>" data-toggle="collapse" data-parent="#navuser" data-target="#userchildmenu-<?php echo (is_string($tmp=$this->globals["foreach"]["menu"]["index"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"><span class="icon icon-chevron-down" role="presentation" aria-hidden="true"></span><span class="nav-title sr-only"><?php echo PluginStr($this, "showmenu", "mahara", null, "".(is_string($tmp=(isset($this->scope["item"]["title"]) ? $this->scope["item"]["title"]:null)) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp)."", null, null, null);?></span></button><?php }
if ((isset($this->scope["item"]["submenu"]) ? $this->scope["item"]["submenu"]:null)) {?><ul id="userchildmenu-<?php echo (is_string($tmp=$this->globals["foreach"]["menu"]["index"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>" class="<?php if ((isset($this->scope["item"]["selected"]) ? $this->scope["item"]["selected"]:null)) {?> show<?php }?> collapse child-nav" role="menu"><?php $_fh12_data = (is_string($tmp=(isset($this->scope["item"]["submenu"]) ? $this->scope["item"]["submenu"]:null)) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);if ($this->isTraversable($_fh12_data) == true){foreach ($_fh12_data as $this->scope['subitem']){/* -- foreach start output */?><li class="<?php if ((isset($this->scope["subitem"]["selected"]) ? $this->scope["subitem"]["selected"]:null)) {?>active <?php }
if ((isset($this->scope["subitem"]["submenu"]) ? $this->scope["subitem"]["submenu"]:null)) {?>has-sub <?php }?>"><a href="<?php echo (is_string($tmp=$this->scope["WWWROOT"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);
echo (is_string($tmp=$this->scope["subitem"]["url"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"<?php if ((isset($this->scope["subitem"]["accesskey"]) ? $this->scope["subitem"]["accesskey"]:null)) {?> accesskey="<?php echo (is_string($tmp=$this->scope["subitem"]["accesskey"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"<?php }?>><?php echo (is_string($tmp=$this->scope["subitem"]["title"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?></a><?php if ((isset($this->scope["subitem"]["submenu"]) ? $this->scope["subitem"]["submenu"]:null)) {?><ul class="dropdown-tertiary"><?php $_fh11_data = (is_string($tmp=(isset($this->scope["subitem"]["submenu"]) ? $this->scope["subitem"]["submenu"]:null)) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);if ($this->isTraversable($_fh11_data) == true){foreach ($_fh11_data as $this->scope['tertiaryitem']){/* -- foreach start output */?><li<?php if ((isset($this->scope["tertiaryitem"]["selected"]) ? $this->scope["tertiaryitem"]["selected"]:null)) {?> class="selected"<?php }?>><a href="<?php echo (is_string($tmp=$this->scope["WWWROOT"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);
echo (is_string($tmp=$this->scope["tertiaryitem"]["url"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"<?php if ((isset($this->scope["tertiaryitem"]["accesskey"]) ? $this->scope["tertiaryitem"]["accesskey"]:null)) {?> accesskey="<?php echo (is_string($tmp=$this->scope["tertiaryitem"]["accesskey"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"<?php }?>><?php echo (is_string($tmp=$this->scope["tertiaryitem"]["title"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?></a></li><?php /* -- foreach end output */}}?></ul><?php }?></li><?php /* -- foreach end output */}}?></ul><?php }?></li><?php /* -- foreach end output */}}?><li class="btn-logout has-icon"><a id="logoutbutton" href="<?php echo (is_string($tmp=$this->scope["WWWROOT"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>?logout" accesskey="l"><span class="icon icon-sign-out-alt" role="presentation" aria-hidden="true"></span><span class="nav-title"><?php echo PluginStr($this, "logout", 'mahara', null, null, null, null, null);?></span></a><script>$('#logoutbutton').click(function(e) {if ($(this).hasClass('disabled')) {e.preventDefault();return false;}$(this).addClass('disabled');return true;});</script></li><?php if ((isset($this->scope["USERMASQUERADING"]) ? $this->scope["USERMASQUERADING"] : null) && (isset($this->scope["LOGGEDIN"]) ? $this->scope["LOGGEDIN"] : null)) {?><li class="backto-be-admin has-icon"><a href="<?php echo (is_string($tmp=$this->scope["becomeyoulink"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>" title="<?php echo (is_string($tmp=$this->scope["becomeyouagain"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?>"><span class="icon icon-undo left" role="presentation"></span><span class="nav-title"><?php echo (is_string($tmp=$this->scope["becomeyouagain"]) ? htmlspecialchars($tmp, ENT_QUOTES, $this->charset) : $tmp);?></span></a></li><?php }?>

    </ul>
  </div>
</nav>
<?php 
}?>

<?php if (! (isset($this->scope["nosearch"]) ? $this->scope["nosearch"] : null) && ( (isset($this->scope["LOGGEDIN"]) ? $this->scope["LOGGEDIN"] : null) || (isset($this->scope["publicsearchallowed"]) ? $this->scope["publicsearchallowed"] : null) )) {
?>

<div class="navbar-form collapse navbar-collapse<?php if ((isset($this->scope["languageform"]) ? $this->scope["languageform"] : null)) {
?> with-langform<?php if (! (isset($this->scope["LOGGEDIN"]) ? $this->scope["LOGGEDIN"] : null) && ! (isset($this->scope["SHOWLOGINBLOCK"]) ? $this->scope["SHOWLOGINBLOCK"] : null) && ! (isset($this->scope["LOGINPAGE"]) ? $this->scope["LOGINPAGE"] : null)) {
?>-login<?php 
}

}?>">
    <?php echo header_search_form();?>

</div>
<?php 
}?>

<?php  /* end template body */
return $this->buffer . ob_get_clean();
?>