<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2020/12/05 14:38:09

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=127.0.0.1;port=3310;dbname=bitnami_orangehrm;charset=utf8mb4',
  'username' => 'bn_orangehrm',
  'password' => '0f74d80972',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
