<?php
// auto-generated by sfSecurityConfigHandler
// date: 2020/12/13 22:11:47
$this->security = array (
  'viewbuzzimage' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
